In [2]:
import cv2

img = cv2.imread("smallgray.png",0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
cv2.imwrite("newimg.png", img)

True

In [7]:
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [9]:
img.shape
img[2,4]

182

In [10]:
img.T

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182]], dtype=uint8)

In [11]:
for row in img:
    print(row)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [13]:
import numpy
n_arr = numpy.hstack((img,img))
n_arr

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
v_arr = numpy.vstack((img,img))
v_arr

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
sh_arr = numpy.hsplit(n_arr, 5)
sh_arr

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8),
 array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8),
 array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]